const CustomerInsert = require("../Customers/custm_INS")

CustomerInsert({
  orgId: 1,
  name: "customer",
  description: 'Descrip del customer',
  website: null,
  isActive: true,
  inActiveReason: null,
  primaryUserID: null,
  primaryContact: null,
  dateCreated: new Date(),
  DateModified: 4,
  creatorID: 3,
  modifierID: 4,
  hasPortalAccess: null,
  createdBy: "paquito",
  lastModifiedBy: "paquito",
  sAExpirationDate: new Date(),
  slaName: "Standard SLA",
  defaultWikiArticleID: 67890,
  defaultSupportGroupID: 101112,
  defaultSupportGroup: "Tech Support",
  defaultSupportUserID: 131415,
  defaultSupportUser: "JohnDoe",
  domains: "example.com, sample.org",
  supportHours: 40,
  supportHoursUsed: 10,
  supportHoursRemaining: 30,
  needsIndexing: true,
  custDisIndex: 5,
  custDistIndexTrend: 2,
  emailTicketActions: "open,close,escalate",
  entityID: 161718
})
