const TicketInsert = require("./ticket_INS")

TicketInsert({
  userId: "2",
  groupId: "4",
  productId: "5",
  orgId: 1,
  solvedVersion: "v1.2.3",
  ticketTypeName: "Bug",
  status: "Open",
  statusPosition: 1,
  reportedVersion: "v1.2.0",
  severityPosition: 2,
  isClosed: false,
  severity: "High",
  ticketNumber: 12345,
  isVisibleOnPortal: true,
  isKnowledgeBase: false,
  reportedVersionID: 101,
  solvedVersionID: 102,
  ticketStatusID: 103,
  ticketTypeID: 104,
  ticketSeverityID: 105,
  name: "Ticket Example",
  parentID: 0,
  modifierID: true,
  creatorID: true,
  dateModified: new Date(),
  dateCreated: new Date(),
  dateClosed: new Date(),
  closerId: null,
  daysClosed: null,
  daysOpened: 5,
  closerName: null,
  cratorName: "JaneDoe",
  modifierName: "JohnDoe",
  hoursSpent: 10,
  slaViolationTime: 2,
  slaWarningTime: 1,
  knowledgeBaseCategoryID: 201,
  knowledgeBaseCategoryName: "Technical Support",
  DueDate: new Date(),
  ticketSource: "Email",
  primaryCustomer: "ACME Corp",
  jiraKey: 67890,
  isSecured: true,
  tags: "urgent,backend",
});
